// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

package ru.mail.kdog.dto;

public final class DtoProtos {
  private DtoProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Page)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UUID uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <code>.UUID uuid = 1;</code>
     */
    ru.mail.kdog.dto.DtoProtos.UUID getUuid();
    /**
     * <code>.UUID uuid = 1;</code>
     */
    ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getUuidOrBuilder();

    /**
     * <code>int32 part_full_count = 2;</code>
     */
    int getPartFullCount();

    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart> 
        getContentPartList();
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    ru.mail.kdog.dto.DtoProtos.ContentPart getContentPart(int index);
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    int getContentPartCount();
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    java.util.List<? extends ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder> 
        getContentPartOrBuilderList();
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder getContentPartOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Page}
   */
  public  static final class Page extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Page)
      PageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Page.newBuilder() to construct.
    private Page(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Page() {
      partFullCount_ = 0;
      contentPart_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Page(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ru.mail.kdog.dto.DtoProtos.UUID.Builder subBuilder = null;
              if (uuid_ != null) {
                subBuilder = uuid_.toBuilder();
              }
              uuid_ = input.readMessage(ru.mail.kdog.dto.DtoProtos.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(uuid_);
                uuid_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              partFullCount_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                contentPart_ = new java.util.ArrayList<ru.mail.kdog.dto.DtoProtos.ContentPart>();
                mutable_bitField0_ |= 0x00000004;
              }
              contentPart_.add(
                  input.readMessage(ru.mail.kdog.dto.DtoProtos.ContentPart.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          contentPart_ = java.util.Collections.unmodifiableList(contentPart_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_Page_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_Page_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mail.kdog.dto.DtoProtos.Page.class, ru.mail.kdog.dto.DtoProtos.Page.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private ru.mail.kdog.dto.DtoProtos.UUID uuid_;
    /**
     * <code>.UUID uuid = 1;</code>
     */
    public boolean hasUuid() {
      return uuid_ != null;
    }
    /**
     * <code>.UUID uuid = 1;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.UUID getUuid() {
      return uuid_ == null ? ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : uuid_;
    }
    /**
     * <code>.UUID uuid = 1;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getUuidOrBuilder() {
      return getUuid();
    }

    public static final int PART_FULL_COUNT_FIELD_NUMBER = 2;
    private int partFullCount_;
    /**
     * <code>int32 part_full_count = 2;</code>
     */
    public int getPartFullCount() {
      return partFullCount_;
    }

    public static final int CONTENTPART_FIELD_NUMBER = 3;
    private java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart> contentPart_;
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    public java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart> getContentPartList() {
      return contentPart_;
    }
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    public java.util.List<? extends ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder> 
        getContentPartOrBuilderList() {
      return contentPart_;
    }
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    public int getContentPartCount() {
      return contentPart_.size();
    }
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.ContentPart getContentPart(int index) {
      return contentPart_.get(index);
    }
    /**
     * <code>repeated .ContentPart contentPart = 3;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder getContentPartOrBuilder(
        int index) {
      return contentPart_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uuid_ != null) {
        output.writeMessage(1, getUuid());
      }
      if (partFullCount_ != 0) {
        output.writeInt32(2, partFullCount_);
      }
      for (int i = 0; i < contentPart_.size(); i++) {
        output.writeMessage(3, contentPart_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uuid_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUuid());
      }
      if (partFullCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, partFullCount_);
      }
      for (int i = 0; i < contentPart_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, contentPart_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.mail.kdog.dto.DtoProtos.Page)) {
        return super.equals(obj);
      }
      ru.mail.kdog.dto.DtoProtos.Page other = (ru.mail.kdog.dto.DtoProtos.Page) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (getPartFullCount()
          == other.getPartFullCount());
      result = result && getContentPartList()
          .equals(other.getContentPartList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      hash = (37 * hash) + PART_FULL_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getPartFullCount();
      if (getContentPartCount() > 0) {
        hash = (37 * hash) + CONTENTPART_FIELD_NUMBER;
        hash = (53 * hash) + getContentPartList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.Page parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.mail.kdog.dto.DtoProtos.Page prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Page}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Page)
        ru.mail.kdog.dto.DtoProtos.PageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_Page_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_Page_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.mail.kdog.dto.DtoProtos.Page.class, ru.mail.kdog.dto.DtoProtos.Page.Builder.class);
      }

      // Construct using ru.mail.kdog.dto.DtoProtos.Page.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContentPartFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (uuidBuilder_ == null) {
          uuid_ = null;
        } else {
          uuid_ = null;
          uuidBuilder_ = null;
        }
        partFullCount_ = 0;

        if (contentPartBuilder_ == null) {
          contentPart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          contentPartBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_Page_descriptor;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.Page getDefaultInstanceForType() {
        return ru.mail.kdog.dto.DtoProtos.Page.getDefaultInstance();
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.Page build() {
        ru.mail.kdog.dto.DtoProtos.Page result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.Page buildPartial() {
        ru.mail.kdog.dto.DtoProtos.Page result = new ru.mail.kdog.dto.DtoProtos.Page(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (uuidBuilder_ == null) {
          result.uuid_ = uuid_;
        } else {
          result.uuid_ = uuidBuilder_.build();
        }
        result.partFullCount_ = partFullCount_;
        if (contentPartBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            contentPart_ = java.util.Collections.unmodifiableList(contentPart_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.contentPart_ = contentPart_;
        } else {
          result.contentPart_ = contentPartBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.mail.kdog.dto.DtoProtos.Page) {
          return mergeFrom((ru.mail.kdog.dto.DtoProtos.Page)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.mail.kdog.dto.DtoProtos.Page other) {
        if (other == ru.mail.kdog.dto.DtoProtos.Page.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          mergeUuid(other.getUuid());
        }
        if (other.getPartFullCount() != 0) {
          setPartFullCount(other.getPartFullCount());
        }
        if (contentPartBuilder_ == null) {
          if (!other.contentPart_.isEmpty()) {
            if (contentPart_.isEmpty()) {
              contentPart_ = other.contentPart_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureContentPartIsMutable();
              contentPart_.addAll(other.contentPart_);
            }
            onChanged();
          }
        } else {
          if (!other.contentPart_.isEmpty()) {
            if (contentPartBuilder_.isEmpty()) {
              contentPartBuilder_.dispose();
              contentPartBuilder_ = null;
              contentPart_ = other.contentPart_;
              bitField0_ = (bitField0_ & ~0x00000004);
              contentPartBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContentPartFieldBuilder() : null;
            } else {
              contentPartBuilder_.addAllMessages(other.contentPart_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.mail.kdog.dto.DtoProtos.Page parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.mail.kdog.dto.DtoProtos.Page) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private ru.mail.kdog.dto.DtoProtos.UUID uuid_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder> uuidBuilder_;
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public boolean hasUuid() {
        return uuidBuilder_ != null || uuid_ != null;
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUID getUuid() {
        if (uuidBuilder_ == null) {
          return uuid_ == null ? ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : uuid_;
        } else {
          return uuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public Builder setUuid(ru.mail.kdog.dto.DtoProtos.UUID value) {
        if (uuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          uuid_ = value;
          onChanged();
        } else {
          uuidBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public Builder setUuid(
          ru.mail.kdog.dto.DtoProtos.UUID.Builder builderForValue) {
        if (uuidBuilder_ == null) {
          uuid_ = builderForValue.build();
          onChanged();
        } else {
          uuidBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public Builder mergeUuid(ru.mail.kdog.dto.DtoProtos.UUID value) {
        if (uuidBuilder_ == null) {
          if (uuid_ != null) {
            uuid_ =
              ru.mail.kdog.dto.DtoProtos.UUID.newBuilder(uuid_).mergeFrom(value).buildPartial();
          } else {
            uuid_ = value;
          }
          onChanged();
        } else {
          uuidBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public Builder clearUuid() {
        if (uuidBuilder_ == null) {
          uuid_ = null;
          onChanged();
        } else {
          uuid_ = null;
          uuidBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUID.Builder getUuidBuilder() {
        
        onChanged();
        return getUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getUuidOrBuilder() {
        if (uuidBuilder_ != null) {
          return uuidBuilder_.getMessageOrBuilder();
        } else {
          return uuid_ == null ?
              ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : uuid_;
        }
      }
      /**
       * <code>.UUID uuid = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder> 
          getUuidFieldBuilder() {
        if (uuidBuilder_ == null) {
          uuidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder>(
                  getUuid(),
                  getParentForChildren(),
                  isClean());
          uuid_ = null;
        }
        return uuidBuilder_;
      }

      private int partFullCount_ ;
      /**
       * <code>int32 part_full_count = 2;</code>
       */
      public int getPartFullCount() {
        return partFullCount_;
      }
      /**
       * <code>int32 part_full_count = 2;</code>
       */
      public Builder setPartFullCount(int value) {
        
        partFullCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 part_full_count = 2;</code>
       */
      public Builder clearPartFullCount() {
        
        partFullCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart> contentPart_ =
        java.util.Collections.emptyList();
      private void ensureContentPartIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          contentPart_ = new java.util.ArrayList<ru.mail.kdog.dto.DtoProtos.ContentPart>(contentPart_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.ContentPart, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder, ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder> contentPartBuilder_;

      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart> getContentPartList() {
        if (contentPartBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contentPart_);
        } else {
          return contentPartBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public int getContentPartCount() {
        if (contentPartBuilder_ == null) {
          return contentPart_.size();
        } else {
          return contentPartBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.ContentPart getContentPart(int index) {
        if (contentPartBuilder_ == null) {
          return contentPart_.get(index);
        } else {
          return contentPartBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder setContentPart(
          int index, ru.mail.kdog.dto.DtoProtos.ContentPart value) {
        if (contentPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentPartIsMutable();
          contentPart_.set(index, value);
          onChanged();
        } else {
          contentPartBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder setContentPart(
          int index, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder builderForValue) {
        if (contentPartBuilder_ == null) {
          ensureContentPartIsMutable();
          contentPart_.set(index, builderForValue.build());
          onChanged();
        } else {
          contentPartBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder addContentPart(ru.mail.kdog.dto.DtoProtos.ContentPart value) {
        if (contentPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentPartIsMutable();
          contentPart_.add(value);
          onChanged();
        } else {
          contentPartBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder addContentPart(
          int index, ru.mail.kdog.dto.DtoProtos.ContentPart value) {
        if (contentPartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContentPartIsMutable();
          contentPart_.add(index, value);
          onChanged();
        } else {
          contentPartBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder addContentPart(
          ru.mail.kdog.dto.DtoProtos.ContentPart.Builder builderForValue) {
        if (contentPartBuilder_ == null) {
          ensureContentPartIsMutable();
          contentPart_.add(builderForValue.build());
          onChanged();
        } else {
          contentPartBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder addContentPart(
          int index, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder builderForValue) {
        if (contentPartBuilder_ == null) {
          ensureContentPartIsMutable();
          contentPart_.add(index, builderForValue.build());
          onChanged();
        } else {
          contentPartBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder addAllContentPart(
          java.lang.Iterable<? extends ru.mail.kdog.dto.DtoProtos.ContentPart> values) {
        if (contentPartBuilder_ == null) {
          ensureContentPartIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contentPart_);
          onChanged();
        } else {
          contentPartBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder clearContentPart() {
        if (contentPartBuilder_ == null) {
          contentPart_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          contentPartBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public Builder removeContentPart(int index) {
        if (contentPartBuilder_ == null) {
          ensureContentPartIsMutable();
          contentPart_.remove(index);
          onChanged();
        } else {
          contentPartBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.ContentPart.Builder getContentPartBuilder(
          int index) {
        return getContentPartFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder getContentPartOrBuilder(
          int index) {
        if (contentPartBuilder_ == null) {
          return contentPart_.get(index);  } else {
          return contentPartBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public java.util.List<? extends ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder> 
           getContentPartOrBuilderList() {
        if (contentPartBuilder_ != null) {
          return contentPartBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contentPart_);
        }
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.ContentPart.Builder addContentPartBuilder() {
        return getContentPartFieldBuilder().addBuilder(
            ru.mail.kdog.dto.DtoProtos.ContentPart.getDefaultInstance());
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.ContentPart.Builder addContentPartBuilder(
          int index) {
        return getContentPartFieldBuilder().addBuilder(
            index, ru.mail.kdog.dto.DtoProtos.ContentPart.getDefaultInstance());
      }
      /**
       * <code>repeated .ContentPart contentPart = 3;</code>
       */
      public java.util.List<ru.mail.kdog.dto.DtoProtos.ContentPart.Builder> 
           getContentPartBuilderList() {
        return getContentPartFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.ContentPart, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder, ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder> 
          getContentPartFieldBuilder() {
        if (contentPartBuilder_ == null) {
          contentPartBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.mail.kdog.dto.DtoProtos.ContentPart, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder, ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder>(
                  contentPart_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          contentPart_ = null;
        }
        return contentPartBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Page)
    }

    // @@protoc_insertion_point(class_scope:Page)
    private static final ru.mail.kdog.dto.DtoProtos.Page DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.mail.kdog.dto.DtoProtos.Page();
    }

    public static ru.mail.kdog.dto.DtoProtos.Page getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Page>
        PARSER = new com.google.protobuf.AbstractParser<Page>() {
      @java.lang.Override
      public Page parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Page(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Page> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Page> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.mail.kdog.dto.DtoProtos.Page getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContentPartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ContentPart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    boolean hasPageUuid();
    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    ru.mail.kdog.dto.DtoProtos.UUID getPageUuid();
    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getPageUuidOrBuilder();

    /**
     * <code>int32 part_num = 2;</code>
     */
    int getPartNum();

    /**
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code ContentPart}
   */
  public  static final class ContentPart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ContentPart)
      ContentPartOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContentPart.newBuilder() to construct.
    private ContentPart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContentPart() {
      partNum_ = 0;
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContentPart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ru.mail.kdog.dto.DtoProtos.UUID.Builder subBuilder = null;
              if (pageUuid_ != null) {
                subBuilder = pageUuid_.toBuilder();
              }
              pageUuid_ = input.readMessage(ru.mail.kdog.dto.DtoProtos.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pageUuid_);
                pageUuid_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              partNum_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_ContentPart_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_ContentPart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mail.kdog.dto.DtoProtos.ContentPart.class, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder.class);
    }

    public static final int PAGE_UUID_FIELD_NUMBER = 1;
    private ru.mail.kdog.dto.DtoProtos.UUID pageUuid_;
    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    public boolean hasPageUuid() {
      return pageUuid_ != null;
    }
    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.UUID getPageUuid() {
      return pageUuid_ == null ? ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : pageUuid_;
    }
    /**
     * <code>.UUID page_uuid = 1;</code>
     */
    public ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getPageUuidOrBuilder() {
      return getPageUuid();
    }

    public static final int PART_NUM_FIELD_NUMBER = 2;
    private int partNum_;
    /**
     * <code>int32 part_num = 2;</code>
     */
    public int getPartNum() {
      return partNum_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageUuid_ != null) {
        output.writeMessage(1, getPageUuid());
      }
      if (partNum_ != 0) {
        output.writeInt32(2, partNum_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageUuid_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPageUuid());
      }
      if (partNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, partNum_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.mail.kdog.dto.DtoProtos.ContentPart)) {
        return super.equals(obj);
      }
      ru.mail.kdog.dto.DtoProtos.ContentPart other = (ru.mail.kdog.dto.DtoProtos.ContentPart) obj;

      boolean result = true;
      result = result && (hasPageUuid() == other.hasPageUuid());
      if (hasPageUuid()) {
        result = result && getPageUuid()
            .equals(other.getPageUuid());
      }
      result = result && (getPartNum()
          == other.getPartNum());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPageUuid()) {
        hash = (37 * hash) + PAGE_UUID_FIELD_NUMBER;
        hash = (53 * hash) + getPageUuid().hashCode();
      }
      hash = (37 * hash) + PART_NUM_FIELD_NUMBER;
      hash = (53 * hash) + getPartNum();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.ContentPart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.mail.kdog.dto.DtoProtos.ContentPart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ContentPart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ContentPart)
        ru.mail.kdog.dto.DtoProtos.ContentPartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_ContentPart_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_ContentPart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.mail.kdog.dto.DtoProtos.ContentPart.class, ru.mail.kdog.dto.DtoProtos.ContentPart.Builder.class);
      }

      // Construct using ru.mail.kdog.dto.DtoProtos.ContentPart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (pageUuidBuilder_ == null) {
          pageUuid_ = null;
        } else {
          pageUuid_ = null;
          pageUuidBuilder_ = null;
        }
        partNum_ = 0;

        content_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_ContentPart_descriptor;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.ContentPart getDefaultInstanceForType() {
        return ru.mail.kdog.dto.DtoProtos.ContentPart.getDefaultInstance();
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.ContentPart build() {
        ru.mail.kdog.dto.DtoProtos.ContentPart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.ContentPart buildPartial() {
        ru.mail.kdog.dto.DtoProtos.ContentPart result = new ru.mail.kdog.dto.DtoProtos.ContentPart(this);
        if (pageUuidBuilder_ == null) {
          result.pageUuid_ = pageUuid_;
        } else {
          result.pageUuid_ = pageUuidBuilder_.build();
        }
        result.partNum_ = partNum_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.mail.kdog.dto.DtoProtos.ContentPart) {
          return mergeFrom((ru.mail.kdog.dto.DtoProtos.ContentPart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.mail.kdog.dto.DtoProtos.ContentPart other) {
        if (other == ru.mail.kdog.dto.DtoProtos.ContentPart.getDefaultInstance()) return this;
        if (other.hasPageUuid()) {
          mergePageUuid(other.getPageUuid());
        }
        if (other.getPartNum() != 0) {
          setPartNum(other.getPartNum());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.mail.kdog.dto.DtoProtos.ContentPart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.mail.kdog.dto.DtoProtos.ContentPart) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ru.mail.kdog.dto.DtoProtos.UUID pageUuid_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder> pageUuidBuilder_;
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public boolean hasPageUuid() {
        return pageUuidBuilder_ != null || pageUuid_ != null;
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUID getPageUuid() {
        if (pageUuidBuilder_ == null) {
          return pageUuid_ == null ? ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : pageUuid_;
        } else {
          return pageUuidBuilder_.getMessage();
        }
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public Builder setPageUuid(ru.mail.kdog.dto.DtoProtos.UUID value) {
        if (pageUuidBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pageUuid_ = value;
          onChanged();
        } else {
          pageUuidBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public Builder setPageUuid(
          ru.mail.kdog.dto.DtoProtos.UUID.Builder builderForValue) {
        if (pageUuidBuilder_ == null) {
          pageUuid_ = builderForValue.build();
          onChanged();
        } else {
          pageUuidBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public Builder mergePageUuid(ru.mail.kdog.dto.DtoProtos.UUID value) {
        if (pageUuidBuilder_ == null) {
          if (pageUuid_ != null) {
            pageUuid_ =
              ru.mail.kdog.dto.DtoProtos.UUID.newBuilder(pageUuid_).mergeFrom(value).buildPartial();
          } else {
            pageUuid_ = value;
          }
          onChanged();
        } else {
          pageUuidBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public Builder clearPageUuid() {
        if (pageUuidBuilder_ == null) {
          pageUuid_ = null;
          onChanged();
        } else {
          pageUuid_ = null;
          pageUuidBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUID.Builder getPageUuidBuilder() {
        
        onChanged();
        return getPageUuidFieldBuilder().getBuilder();
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      public ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder getPageUuidOrBuilder() {
        if (pageUuidBuilder_ != null) {
          return pageUuidBuilder_.getMessageOrBuilder();
        } else {
          return pageUuid_ == null ?
              ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance() : pageUuid_;
        }
      }
      /**
       * <code>.UUID page_uuid = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder> 
          getPageUuidFieldBuilder() {
        if (pageUuidBuilder_ == null) {
          pageUuidBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ru.mail.kdog.dto.DtoProtos.UUID, ru.mail.kdog.dto.DtoProtos.UUID.Builder, ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder>(
                  getPageUuid(),
                  getParentForChildren(),
                  isClean());
          pageUuid_ = null;
        }
        return pageUuidBuilder_;
      }

      private int partNum_ ;
      /**
       * <code>int32 part_num = 2;</code>
       */
      public int getPartNum() {
        return partNum_;
      }
      /**
       * <code>int32 part_num = 2;</code>
       */
      public Builder setPartNum(int value) {
        
        partNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 part_num = 2;</code>
       */
      public Builder clearPartNum() {
        
        partNum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ContentPart)
    }

    // @@protoc_insertion_point(class_scope:ContentPart)
    private static final ru.mail.kdog.dto.DtoProtos.ContentPart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.mail.kdog.dto.DtoProtos.ContentPart();
    }

    public static ru.mail.kdog.dto.DtoProtos.ContentPart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContentPart>
        PARSER = new com.google.protobuf.AbstractParser<ContentPart>() {
      @java.lang.Override
      public ContentPart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContentPart(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContentPart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContentPart> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.mail.kdog.dto.DtoProtos.ContentPart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UUIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UUID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code UUID}
   */
  public  static final class UUID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UUID)
      UUIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UUID.newBuilder() to construct.
    private UUID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UUID() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UUID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_UUID_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mail.kdog.dto.DtoProtos.internal_static_UUID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mail.kdog.dto.DtoProtos.UUID.class, ru.mail.kdog.dto.DtoProtos.UUID.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.mail.kdog.dto.DtoProtos.UUID)) {
        return super.equals(obj);
      }
      ru.mail.kdog.dto.DtoProtos.UUID other = (ru.mail.kdog.dto.DtoProtos.UUID) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mail.kdog.dto.DtoProtos.UUID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.mail.kdog.dto.DtoProtos.UUID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UUID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UUID)
        ru.mail.kdog.dto.DtoProtos.UUIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_UUID_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_UUID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.mail.kdog.dto.DtoProtos.UUID.class, ru.mail.kdog.dto.DtoProtos.UUID.Builder.class);
      }

      // Construct using ru.mail.kdog.dto.DtoProtos.UUID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.mail.kdog.dto.DtoProtos.internal_static_UUID_descriptor;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.UUID getDefaultInstanceForType() {
        return ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance();
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.UUID build() {
        ru.mail.kdog.dto.DtoProtos.UUID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ru.mail.kdog.dto.DtoProtos.UUID buildPartial() {
        ru.mail.kdog.dto.DtoProtos.UUID result = new ru.mail.kdog.dto.DtoProtos.UUID(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.mail.kdog.dto.DtoProtos.UUID) {
          return mergeFrom((ru.mail.kdog.dto.DtoProtos.UUID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.mail.kdog.dto.DtoProtos.UUID other) {
        if (other == ru.mail.kdog.dto.DtoProtos.UUID.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.mail.kdog.dto.DtoProtos.UUID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.mail.kdog.dto.DtoProtos.UUID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UUID)
    }

    // @@protoc_insertion_point(class_scope:UUID)
    private static final ru.mail.kdog.dto.DtoProtos.UUID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.mail.kdog.dto.DtoProtos.UUID();
    }

    public static ru.mail.kdog.dto.DtoProtos.UUID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UUID>
        PARSER = new com.google.protobuf.AbstractParser<UUID>() {
      @java.lang.Override
      public UUID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UUID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UUID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UUID> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ru.mail.kdog.dto.DtoProtos.UUID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Page_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Page_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ContentPart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ContentPart_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UUID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UUID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Messages.proto\"W\n\004Page\022\023\n\004uuid\030\001 \001(\0132\005" +
      ".UUID\022\027\n\017part_full_count\030\002 \001(\005\022!\n\013conten" +
      "tPart\030\003 \003(\0132\014.ContentPart\"J\n\013ContentPart" +
      "\022\030\n\tpage_uuid\030\001 \001(\0132\005.UUID\022\020\n\010part_num\030\002" +
      " \001(\005\022\017\n\007content\030\003 \001(\t\"\025\n\004UUID\022\r\n\005value\030\001" +
      " \001(\tB\035\n\020ru.mail.kdog.dtoB\tDtoProtosb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Page_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Page_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Page_descriptor,
        new java.lang.String[] { "Uuid", "PartFullCount", "ContentPart", });
    internal_static_ContentPart_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ContentPart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ContentPart_descriptor,
        new java.lang.String[] { "PageUuid", "PartNum", "Content", });
    internal_static_UUID_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UUID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UUID_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
